# Generated by Django 4.1 on 2026-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
