# Generated by Django 5.2.14 on 2026-05-09 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_persona_sedes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='area',
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='inv.sede')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['sede', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='inv.grupo'),
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos', to='inv.grupo')),
            ],
            options={
                'verbose_name': 'Subgrupo',
                'verbose_name_plural': 'Subgrupos',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='inv.subgrupo'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('sede', 'nombre'), name='unique_grupo_por_sede'),
        ),
        migrations.AddConstraint(
            model_name='subgrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'nombre'), name='unique_subgrupo_por_grupo'),
        ),
    ]
